version: '3.1'
services:
  nodeapp:
    image: node:18
    container_name: nodeapp
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: npm install -g npm@9.6.2 & npm install & node app/index.js
    environment:
      - NODE_PORT=3000
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb