version: '3.1'
services:
  nodeapp:
    image: yohav08/nodeapp
    container_name: nodeapp-mongo
    ports:
      - 3000:3000
    volumes:
      - ./:/code
    environment:
      - NODE_PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydb